name: CI
on:
  push: { branches: [main] }
  pull_request: {}

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Configure
        run: cd game && cmake --preset dev
      - name: Build
        run: cd game && cmake --build build/dev -j 4
      - name: Test
        run: cd game && ctest --test-dir build/dev --output-on-failure

  asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Configure (ASAN)
        run: cd game && cmake --preset asan
      - name: Build (ASAN)
        run: cd game && cmake --build build/asan -j 4
      - name: Test (ASAN)
        run: cd game && ctest --test-dir build/asan --output-on-failure
